stop_lookup:
  name: Stop lookup
  description: Search for public transport stops by name using Trafiklab API
  fields:
    api_key:
      name: API Key
      description: Your Trafiklab API key
      required: true
      selector:
        text:
          type: password
    search_query:
      name: Search query
      description: Search string to find stops (minimum 1 character)
      required: true
      example: "Stockholm"
      selector:
        text:
  response:
    type: object
    properties:
      search_query:
        type: string
        description: The search query that was used
      total_stops:
        type: integer
        description: Total number of stops found
      stops_found:
        type: array
        description: List of stops found matching the search criteria
        items:
          type: object
          properties:
            id:
              type: string
              description: Stop/area ID
            name:
              type: string
              description: Stop/area name
            area_type:
              type: string
              description: Type of area (e.g., META_STOP, STOP_AREA)
            transport_modes:
              type: array
              description: Available transport modes
              items:
                type: string
            average_daily_departures:
              type: number
              description: Average daily departures from this stop
            child_stops:
              type: array
              description: Individual stops within this area
              items:
                type: object
                properties:
                  id:
                    type: string
                    description: Individual stop ID
                  name:
                    type: string
                    description: Individual stop name
                  lat:
                    type: number
                    description: Latitude coordinate
                  lon:
                    type: number
                    description: Longitude coordinate
      error:
        type: string
        description: Error message if the lookup failed
