stop_lookup:
  name: Stop lookup
  description: Search for public transport stops by name using Trafiklab API
  fields:
    api_key:
      name: API Key
      description: Your Trafiklab API key
      required: true
      selector:
        text:
          type: password
    search_query:
      name: Search query
      description: Search string to find stops (minimum 1 character)
      required: true
      example: "Stockholm"
      selector:
        text:
